export const GET_ITEM_REQUEST = "GET_ITEM_REQUEST"
export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS"
export const GET_ITEM_FAILURE = "GET_ITEM_FAILURE"

export const PAGINATE_ITEM_REQUEST = "PAGINATE_ITEM_REQUEST"
export const PAGINATE_ITEM_SUCCESS = "PAGINATE_ITEM_SUCCESS"
export const PAGINATE_ITEM_FAILURE = "PAGINATE_ITEM_FAILURE"

export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST"
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS"
export const ADD_ITEM_FAILURE = "ADD_ITEM_FAILURE"

export const UPDATE_ITEM_REQUEST = "UPDATE_ITEM_REQUEST"
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS"
export const UPDATE_ITEM_FAILURE = "UPDATE_ITEM_FAILURE"

export const UPDATE_STATUS_ITEM_REQUEST = "UPDATE_STATUS_ITEM_REQUEST"
export const UPDATE_STATUS_ITEM_SUCCESS = "UPDATE_STATUS_ITEM_SUCCESS"
export const UPDATE_STATUS_ITEM_FAILURE = "UPDATE_STATUS_ITEM_FAILURE"

export const UPDATE_STATUS_EDITING_REQUEST = "UPDATE_STATUS_EDITING_REQUEST"
export const UPDATE_STATUS_EDITING_SUCCESS = "UPDATE_STATUS_EDITING_SUCCESS"
export const UPDATE_STATUS_EDITING_FAILURE = "UPDATE_STATUS_EDITING_FAILURE"

export const REMOVE_ITEM_REQUEST = "REMOVE_ITEM_REQUEST"
export const REMOVE_ITEM_SUCCESS = "REMOVE_ITEM_SUCCESS"
export const REMOVE_ITEM_FAILURE = "REMOVE_ITEM_FAILURE"

export const URL = `http://localhost:3005/list/`